---

all:
  children:
    cluster:
      vars:
        # common connection opts
        ansible_user: root
        ansible_connection: docker
        become: true
        become_user: root
        ignore_role_errors: false

        # common cartridge opts
        cartridge_app_name: myapp
        cartridge_cluster_cookie: secret-cookie
        cartridge_package_path: ./packages/myapp-1.0.0-0.rpm

        cartridge_bootstrap_vshard: true

      # instances
      hosts:
        core-1:
          config:
            advertise_uri: 'vm1:3101'
            http_port: 8101

        core-2:
          config:
            advertise_uri: 'vm1:3102'
            http_port: 8102

        core-3:
          config:
            advertise_uri: 'vm1:3103'
            http_port: 8103

        core-4:
          config:
            advertise_uri: 'vm1:3104'
            http_port: 8104

        core-5:
          config:
            advertise_uri: 'vm1:3105'
            http_port: 8105

      children:
        # group by hosts
        machine_1:
          vars:
            ansible_host: vm1

          hosts:
            core-1:
            core-2:
            core-3:
            core-4:
            core-5:

        # group by replica sets
        core_replicaset:
          hosts:
            core-1:
            core-2:
            core-3:
            core-4:
            core-5:
          vars:
            replicaset_alias: core
            failover_priority:
              - core-1
              - core-2
              - core-3
              - core-4
              - core-5
            roles:
              - app.roles.custom
              - vshard-router
              - failover-coordinator
