---
- name: Converge
  hosts: cluster
  vars:
    cartridge_app_name: 'myapp'
    # cartridge_scenario:
    #   - edit_topology
  roles:
    - ansible-cartridge
  become: true
  become_user: root
  gather_facts: false
